# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
    # Schedule updates (each hour)
    schedule: [{cron: "0 * * * *"}]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
        push: {branches: ["master", "main"]}
        jobs:
            github-metrics:
                runs-on: ubuntu-latest
                permissions:
                    contents: write
                    steps:
                        - uses: KeoFoxy/KeoFoxy@latest
                        with:
                            # Current configuration doesn't require a GitHub token
                            token: NOT_NEEDED

# Options
user: KeoFoxy
template: classic
base: ""
config_timezone: Europe/Moscow
plugin_anilist: yes
plugin_anilist_limit: 10
plugin_anilist_limit_characters: 20
plugin_anilist_medias: anime, manga
plugin_anilist_sections: favorites, characters
plugin_anilist_user: KeoFoxy
