name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 15 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_ANIME }}
          filename: github-metrics-anime.svg
          #output_action: pull-request
          base: ""
          config_timezone: Europe/Moscow
          plugin_anilist: yes
          plugin_anilist_limit: 5
          plugin_anilist_limit_characters: 20
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: keofoxy

    #  - uses: lowlighter/metrics@latest
    #    with:
    #      token: ${{ secrets.METRICS_TOKEN }}
    #      filename: github-metrics-twitter.svg
    #      base: ""
          plugin_tweets: yes
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: FoxyKeo
          
          
  lines:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_ANIME }}
          committer_token: ${{ secrets.METRICS_ANIME }}
          base: "repositories"
          plugin_lines: yes

  top_langs:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: top_lang.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_ANIME }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.METRICS_ANIME }}

          # Options
          user: KeoFoxy
          template: classic
          base: ""
          config_timezone: ${{ secrets.METRICS_ANIME }}
          plugin_followup: no
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: yes
          plugin_languages_details: lines, bytes-size

