name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_ANIME }}
          base: ""
          config_timezone: Europe/Moscow
          plugin_anilist: yes
          plugin_anilist_limit: 5
          plugin_anilist_limit_characters: 20
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: keofoxy
          plugin_tweets: yes
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: foxykeo
